# Generated by Django 4.0.5 on 2022-06-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='N_apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('household', models.CharField(max_length=100)),
                ('dong', models.CharField(max_length=100)),
                ('flat', models.CharField(max_length=100)),
                ('d_price', models.CharField(max_length=100)),
                ('c_price', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('i_url', models.CharField(max_length=100)),
            ],
        ),
    ]
